In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
l=[]
l=a.tolist()
print(l)

[1, 2, 3, 4, 5]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a=a.reshape(4,4)
print(np.trace(a))

34


In [ ]:
x=int(input("saisir X"))
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
s=""
for i in a:
  if i > x:
    s=s+ str(i)+","
print(s,"are higher than",x)

saisir X8
9,10,11,12,13,14,15,16, are higher than 8


In [25]:
A=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
B=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
C=np.zeros(len(A))
for i in range(len(A)):
  C[i]=A[i]+B[i]
print(C)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]


In [30]:
A=np.array([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0])
A=A.reshape(4,4)
for i in range(4):
  row=A[i,:]
  for j in range(4):
    A[i,j]=A[i,j]-np.mean(row,dtype="float64")
print(A)

[[-1.5        0.125      1.59375    2.9453125]
 [-1.5        1.125      3.34375    5.2578125]
 [-1.5        2.125      5.09375    7.5703125]
 [-1.5        3.125      6.84375    9.8828125]]
